const sentenceBank = [
    "How's your day going?",
    "Could be better.",
    "What happened?",
    "I have a stomach bug.",
    "I was throwing up all night.",
    "Are you feeling better today?",
    "I'm feeling better.",
    "I can eat normally now.",
    "How have you been?",
    "I've been busy with work.",
    "I hope things get better soon.",
    "What do you mean?",
    "Let me think about it.",
    "That makes sense.",
    "I'm not sure yet.",
    "It depends.",
    "I'll check and let you know.",
    "Give me a second.",
    "I'll get back to you.",
    "I'm on my way.",
    "I'll take a look.",
    "Are you almost here?",
    "What's going on?",
    "Does that make sense?",
    "Are you sure?",
    "Wait a second.",
    "How come?",
    "I have no idea.",
    "What are you talking about?",
    "Sounds good.",
    "I don't think so.",
    "Seriously?",
    "I knew it!",
    "It's up to you.",
    "I don't care.",
    "What's wrong?",
    "Is everything okay?",
    "How did it go?",
    "Are you ready?",
    "Let me check.",
    "I'll be right back.",
    "I'm on it.",
    "Are you close?",
    "Is the pool closed?",
    "I should be there in about ten minutes.",
    "I just left the station.",
    "Do you know which entrance to use?",
    "We still have some time.",
    "The tracking says it was delivered.",
    "Maybe they dropped it off at the wrong address.",
    "Hi, I’m calling about my reservation.",
    "How long will it take?",
    "We can text you when it’s ready.",
    "Me neither.",
    "I saw it on the departure board.",
    "I locked myself out.",
    "What are you in the mood for?",
    "What are you up to later?",
    "Not much.",
    "Is this the line for the buffet?",
    "Is my food ready?",
    "I'm just browsing.",
    "I'll take two.",
    "Where can I catch the train?",
    "No, I missed it.",
    "Do you have time for a quick chat?",
    "What's on your mind?",
    "I was wondering if you could help me with this.",
    "No worries, let me take a look.",
    "I didn't catch that.",
    "Does that work for you?",
    "That works for me.",
    "I'll figure it out.",
    "How do I get there?",
    "Go ahead.",
    "Here you go.",
    "What do you think?",
    "I don't mind.",
    "Take your time.",
    "I didn't mean to.",
    "I'm not following.",
    "Do you want me to help you with that?",
    "I'm looking for the train station.",
    "That works.",
    "I'll tell you when we meet.",
    "I need to go over something with you.",
    "I need to go through something with you.",
    "I made it just in time.",
    "We made it!",
    "I can't make it tonight.",
    "We're getting hot pot.",
    "How long is the wait?",
    "Everyone calls me Samuel.",
    "I go by Samuel.",
    "You can call me Samuel.",
    "I'm down.",
    "I just got off work.",
    "I just got to work.",
    "I'm here to pick up my order.",
    "Not necessarily.",
    "Where are you getting off?",
    "Have you seen that movie yet?",
    "Not yet.",
    "I'm kind of tired.",
    "What kind of food do you like?",
    "Sometimes staying in is exactly what you need.",
    "There’s a new café downtown. I thought we could check it out.",
    "Excuse me, where is the restroom?",
    "How much is this?",
    "Can I get the check, please?",
    "Do you accept credit cards?",
    "Can I have a receipt, please?",
    "I’m just looking, thanks.",
    "Can I get a coffee?",
    "Can I get this to go?",
    "Can you drop me off here?",
    "How many are in your party?",
    "What floor is our room on?",
    "What time is breakfast?",
    "What time is it open?",
    "Do you have another hair dryer? Mine is broken.",
    "When can I get my deposit back?",
    "Where is the line for the buffet?",
    "Could you take me to the airport?",
    "Where is the nearest convenience store?",
    "What should I do next?",
    "What’s the difference between this one and the last one?",
    "I don't really follow sports.",
    "I haven’t thought about that.",
    "How did that work?",
    "Could I get a double room?",
    "I want both.",
    "Can you bring us some water?",
    "Yes, that’s correct.",
    "Can I use the restroom?",
    "Are you asking about...?",
    "It’s rush hour.",
    "I’ll be there.",
    "Is there a drop-off point there?",
    "Just stop here.",
    "I should get there by 10:30.",
    "All good?",
    "It’s right here.",
    "It’s sold out.",
    "Is this seat taken?",
    "Just around the corner.",
    "Pretty much.",
    "I’m done.",
    "Over there.",
    "Pretty good.",
    "Anything I should know?",
    "Do you have this in a large?",
    "I’ve already paid for this online.",
    "Do you mean this?",
    "You’re all set.",
    "Not really.",
    "Sorry, I didn’t notice.",
    "Put it back.",
    "Do you have this in stock?",
    "This should only take a minute.",
    "Is breakfast included?",
    "Are you still open?",
    "It’s straight ahead.",
    "What time does the shuttle leave?",
    "How can I help you?",
    "Is there an extra charge for that?",
    "Will that be all?",
    "Sorry to bother you.",
    "Excuse me, could you speak more slowly, please?",
    "Right this way.",
    "Could I have a to-go box?",
    "How do I join?",
    "It’ll be about a 15-minute wait.",
    "You can let me out here.",
    "My food hasn’t come yet.",
    "Can we sit by the window?",
    "What activities are available?",
    "Will this be open later?",
    "My food just got here.",
    "I’ll take this one.",
    "The reservation is under Shang Ji He.",
    "How does this work?",
    "How much is parking per hour?",
    "I have a rental car booked.",
    "Still or sparkling?",
    "Do you have any non-alcoholic drinks?",
    "I'm looking forward to it.",
    "I'm about to head out.",
    "We ran out of water.",
    "Sorry, I got lost.",
    "Where do I check in?",
    "What time do we have to check out?",
    "Do I need to book in advance?",
    "Take this just in case.",
    "No problem.",
    "It turned out fine.",
    "It'll work out.",
    "So far, so good.",
    "I feel like getting something to eat.",
    "We ended up staying home.",
    "I almost gave up.",
    "Just throw it away.",
    "I can do it on my own.",
    "Slow down a little.",
    "Are we supposed to wait here?",
    "I'll come back later.",
    "I fell asleep on the train.",
    "Do I need to fill this out?",
    "Look out!",
    "I just woke up.",
    "Can you turn it off?",
    "I'm fed up with this.",
    "I wonder if they're still open.",
    "If I were you, I'd book it now.",
    "I'll be there as soon as possible.",
    "Why not?"
];
